In [3]:
import os

print(os.getcwd())

C:\Users\omare\Road Accidents Analysis

In [5]:
import pandas as pd

car = pd.read_csv("data/caract-2024.csv")
lieux = pd.read_csv("data/lieux-2024.csv")
usa = pd.read_csv("data/usagers-2024.csv")
veh = pd.read_csv("data/vehicules-2024.csv")

ParserError: Error tokenizing data. C error: Expected 3 fields in line 618, saw 4

In [6]:
import os

print(os.listdir("data"))

['.ipynb_checkpoints', 'caract-2024.csv', 'lieux-2024.csv', 'usagers-2024.csv', 'vehicules-2024.csv']

In [8]:
import os

print(os.path.exists("data/caract-2024.csv"))

True

In [9]:
import os

print(os.getcwd())
print(os.listdir())
print(os.listdir("data"))

C:\Users\omare\Road Accidents Analysis
['.ipynb_checkpoints', '01_data_understanding.ipynb', 'data', 'Untitled.ipynb']
['.ipynb_checkpoints', 'caract-2024.csv', 'lieux-2024.csv', 'usagers-2024.csv', 'vehicules-2024.csv']

In [11]:
with open("data/caract-2024.csv", "r", encoding="utf-8") as f:
    for i in range(5):
        print(f.readline())

"Num_Acc";"jour";"mois";"an";"hrmn";"lum";"dep";"com";"agg";"int";"atm";"col";"adr";"lat";"long"

"202400000001";"25";"03";"2024";"07:40";"2";"70";"70285";"1";"1";"5";"1";"D438";"47,56277000";"6,75832000"

"202400000002";"20";"03";"2024";"15:05";"1";"21";"21054";"2";"3";"7";"6";"HOTEL DIEU (RUE DE L')";"47,02109000";"4,83755000"

"202400000003";"22";"03";"2024";"19:30";"2";"15";"15012";"1";"1";"1";"6";"Allée des Tilleuls";"44,90238400";"2,49641800"

"202400000004";"24";"03";"2024";"17:50";"1";"14";"14118";"2";"3";"7";"3";"128 Rue d'Authie";"49,19166000";" -0,39851000"

In [1]:
with open("data/caract-2024.csv", "rb") as f:
    print(f.read(300))

b'"Num_Acc";"jour";"mois";"an";"hrmn";"lum";"dep";"com";"agg";"int";"atm";"col";"adr";"lat";"long"\n"202400000001";"25";"03";"2024";"07:40";"2";"70";"70285";"1";"1";"5";"1";"D438";"47,56277000";"6,75832000"\n"202400000002";"20";"03";"2024";"15:05";"1";"21";"21054";"2";"3";"7";"6";"HOTEL DIEU (RUE DE L\')'

In [2]:
import pandas as pd

car = pd.read_csv(
    "data/caract-2024.csv",
    sep=";",
    encoding="utf-8",
    engine="python"
)

car.head()

,Num_Acc,jour,mois,an,hrmn,lum,dep,com,agg,int,atm,col,adr,lat,long
0,202400000001,25,3,2024,07:40,2,70,70285,1,1,5,1,D438,"47,56277000","6,75832000"
1,202400000002,20,3,2024,15:05,1,21,21054,2,3,7,6,HOTEL DIEU (RUE DE L'),"47,02109000","4,83755000"
2,202400000003,22,3,2024,19:30,2,15,15012,1,1,1,6,Allée des Tilleuls,"44,90238400","2,49641800"
3,202400000004,24,3,2024,17:50,1,14,14118,2,3,7,3,128 Rue d'Authie,"49,19166000","-0,39851000"
4,202400000005,25,3,2024,19:35,5,13,13106,1,3,2,5,BEDOULE (CHEMIN DE LA),"43,39000000","5,35000000"

In [3]:
import pandas as pd

car = pd.read_csv(
    "data/caract-2024.csv",
    sep=";",
    encoding="utf-8",
    engine="python",
    on_bad_lines="skip"
)

print(car.head())
print(car.shape)

        Num_Acc  jour  mois    an   hrmn  lum dep    com  agg  int  atm  col  \
0  202400000001    25     3  2024  07:40    2  70  70285    1    1    5    1
1  202400000002    20     3  2024  15:05    1  21  21054    2    3    7    6
2  202400000003    22     3  2024  19:30    2  15  15012    1    1    1    6
3  202400000004    24     3  2024  17:50    1  14  14118    2    3    7    3
4  202400000005    25     3  2024  19:35    5  13  13106    1    3    2    5

                      adr          lat          long
0                    D438  47,56277000    6,75832000
1  HOTEL DIEU (RUE DE L')  47,02109000    4,83755000
2      Allée des Tilleuls  44,90238400    2,49641800
3        128 Rue d'Authie  49,19166000   -0,39851000
4  BEDOULE (CHEMIN DE LA)  43,39000000    5,35000000
(54402, 15)

In [4]:
with open("data/caract-2024.csv", "r", encoding="utf-8") as file:
    for line_number, line in enumerate(file, start=1):
        if line_number == 618:
            print(line)
            break

"202400000617";"1";"05";"2024";"07:50";"1";"987";"98715";"2";"1";"1";"3";"Avenue Aratia Nelson Mandela,";" -17,54620200";" -149,58200700"

In [5]:
with open("data/caract-2024.csv", "r", encoding="utf-8") as file:
    lines = file.readlines()

for i in range(616, 619):
    print(f"Line {i+1}:")
    print(lines[i])
    print("-" * 80)

Line 617:
"202400000616";"13";"08";"2024";"12:40";"1";"64";"64445";"2";"1";"2";"2";"JEAN MERMOZ";"43,31521713";" -0,37786558"

--------------------------------------------------------------------------------
Line 618:
"202400000617";"1";"05";"2024";"07:50";"1";"987";"98715";"2";"1";"1";"3";"Avenue Aratia Nelson Mandela,";" -17,54620200";" -149,58200700"

--------------------------------------------------------------------------------
Line 619:
"202400000618";"12";"08";"2024";"15:45";"1";"64";"64445";"2";"1";"1";"3";"ALSACE LORRAINE D'";"43,30350000";" -0,36455000"

--------------------------------------------------------------------------------

In [6]:
import csv

with open("data/caract-2024.csv", "r", encoding="utf-8") as file:
    reader = csv.reader(file, delimiter=";", quotechar='"')

    for i, row in enumerate(reader, start=1):
        if len(row) != 15:
            print(f"Line {i}: {len(row)} fields")
            print(row)
            break

Line 54404: 0 fields
[]

In [7]:
import pandas as pd

car = pd.read_csv(
    "data/caract-2024.csv",
    sep=";",
    encoding="utf-8",
    engine="python"
)

print(car.head())
print(car.shape)

        Num_Acc  jour  mois    an   hrmn  lum dep    com  agg  int  atm  col  \
0  202400000001    25     3  2024  07:40    2  70  70285    1    1    5    1
1  202400000002    20     3  2024  15:05    1  21  21054    2    3    7    6
2  202400000003    22     3  2024  19:30    2  15  15012    1    1    1    6
3  202400000004    24     3  2024  17:50    1  14  14118    2    3    7    3
4  202400000005    25     3  2024  19:35    5  13  13106    1    3    2    5

                      adr          lat          long
0                    D438  47,56277000    6,75832000
1  HOTEL DIEU (RUE DE L')  47,02109000    4,83755000
2      Allée des Tilleuls  44,90238400    2,49641800
3        128 Rue d'Authie  49,19166000   -0,39851000
4  BEDOULE (CHEMIN DE LA)  43,39000000    5,35000000
(54402, 15)

In [8]:
import pandas as pd

car = pd.read_csv(
    "data/caract-2024.csv",
    sep=";",
    encoding="utf-8",
    quotechar='"',
    skip_blank_lines=True,
    low_memory=False
)

print(car.head())
print(car.shape)

        Num_Acc  jour  mois    an   hrmn  lum dep    com  agg  int  atm  col  \
0  202400000001    25     3  2024  07:40    2  70  70285    1    1    5    1
1  202400000002    20     3  2024  15:05    1  21  21054    2    3    7    6
2  202400000003    22     3  2024  19:30    2  15  15012    1    1    1    6
3  202400000004    24     3  2024  17:50    1  14  14118    2    3    7    3
4  202400000005    25     3  2024  19:35    5  13  13106    1    3    2    5

                      adr          lat          long
0                    D438  47,56277000    6,75832000
1  HOTEL DIEU (RUE DE L')  47,02109000    4,83755000
2      Allée des Tilleuls  44,90238400    2,49641800
3        128 Rue d'Authie  49,19166000   -0,39851000
4  BEDOULE (CHEMIN DE LA)  43,39000000    5,35000000
(54402, 15)

In [9]:
car.info()

<class 'pandas.DataFrame'>
RangeIndex: 54402 entries, 0 to 54401
Data columns (total 15 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Num_Acc  54402 non-null  int64
 1   jour     54402 non-null  int64
 2   mois     54402 non-null  int64
 3   an       54402 non-null  int64
 4   hrmn     54402 non-null  str
 5   lum      54402 non-null  int64
 6   dep      54402 non-null  str
 7   com      54402 non-null  str
 8   agg      54402 non-null  int64
 9   int      54402 non-null  int64
 10  atm      54402 non-null  int64
 11  col      54402 non-null  int64
 12  adr      52092 non-null  str
 13  lat      54402 non-null  str
 14  long     54402 non-null  str
dtypes: int64(9), str(6)
memory usage: 6.2 MB

In [10]:
car.describe(include="all")

,Num_Acc,jour,mois,an,hrmn,lum,dep,com,agg,int,atm,col,adr,lat,long
count,5.440200e+04,54402.000000,54402.000000,54402.0,54402,54402.000000,54402,54402,54402.000000,54402.000000,54402.000000,54402.000000,52092,54402,54402
unique,NaN,NaN,NaN,NaN,1414,NaN,107,11285,NaN,NaN,NaN,NaN,28871,52471,52742
top,NaN,NaN,NaN,NaN,18:00,NaN,75,97302,NaN,NaN,NaN,NaN,A86,"48,91936344","5,40000000"
freq,NaN,NaN,NaN,NaN,677,NaN,4191,479,NaN,NaN,NaN,NaN,452,8,9
mean,2.024000e+11,15.665490,6.615749,2024.0,NaN,1.949708,NaN,NaN,1.625161,2.108195,1.677493,4.018069,NaN,NaN,NaN
std,1.570465e+04,8.737761,3.361701,0.0,NaN,1.488462,NaN,NaN,0.484086,2.042602,1.736956,1.984560,NaN,NaN,NaN
min,2.024000e+11,1.000000,1.000000,2024.0,NaN,1.000000,NaN,NaN,1.000000,1.000000,1.000000,-1.000000,NaN,NaN,NaN
25%,2.024000e+11,8.000000,4.000000,2024.0,NaN,1.000000,NaN,NaN,1.000000,1.000000,1.000000,3.000000,NaN,NaN,NaN
50%,2.024000e+11,16.000000,7.000000,2024.0,NaN,1.000000,NaN,NaN,2.000000,1.000000,1.000000,3.000000,NaN,NaN,NaN
75%,2.024000e+11,23.000000,10.000000,2024.0,NaN,3.000000,NaN,NaN,2.000000,2.000000,1.000000,6.000000,NaN,NaN,NaN
max,2.024001e+11,31.000000,12.000000,2024.0,NaN,5.000000,NaN,NaN,2.000000,9.000000,9.000000,7.000000,NaN,NaN,NaN

In [11]:
car.isnull().sum()

Num_Acc       0
jour          0
mois          0
an            0
hrmn          0
lum           0
dep           0
com           0
agg           0
int           0
atm           0
col           0
adr        2310
lat           0
long          0
dtype: int64

In [12]:
car.duplicated().sum()

np.int64(0)

In [13]:
car.nunique()

Num_Acc    54402
jour          31
mois          12
an             1
hrmn        1414
lum            5
dep          107
com        11285
agg            2
int            9
atm            9
col            8
adr        28871
lat        52471
long       52742
dtype: int64

In [14]:
car.dtypes

Num_Acc    int64
jour       int64
mois       int64
an         int64
hrmn         str
lum        int64
dep          str
com          str
agg        int64
int        int64
atm        int64
col        int64
adr          str
lat          str
long         str
dtype: object

In [2]:
import pandas as pd

car = pd.read_csv(
    "data/caract-2024.csv",
    sep=";",
    encoding="utf-8",
    quotechar='"',
    skip_blank_lines=True,
    low_memory=False
)

print(car.shape)

(54402, 15)

In [3]:
car.head()

,Num_Acc,jour,mois,an,hrmn,lum,dep,com,agg,int,atm,col,adr,lat,long
0,202400000001,25,3,2024,07:40,2,70,70285,1,1,5,1,D438,"47,56277000","6,75832000"
1,202400000002,20,3,2024,15:05,1,21,21054,2,3,7,6,HOTEL DIEU (RUE DE L'),"47,02109000","4,83755000"
2,202400000003,22,3,2024,19:30,2,15,15012,1,1,1,6,Allée des Tilleuls,"44,90238400","2,49641800"
3,202400000004,24,3,2024,17:50,1,14,14118,2,3,7,3,128 Rue d'Authie,"49,19166000","-0,39851000"
4,202400000005,25,3,2024,19:35,5,13,13106,1,3,2,5,BEDOULE (CHEMIN DE LA),"43,39000000","5,35000000"

In [5]:
car_clean = car.copy()

In [6]:
car_clean.dtypes

Num_Acc    int64
jour       int64
mois       int64
an         int64
hrmn         str
lum        int64
dep          str
com          str
agg        int64
int        int64
atm        int64
col        int64
adr          str
lat          str
long         str
dtype: object

In [7]:
car_clean["lat"] = (
    car_clean["lat"]
    .str.replace(",", ".", regex=False)
    .str.strip()
    .astype(float)
)

car_clean["long"] = (
    car_clean["long"]
    .str.replace(",", ".", regex=False)
    .str.strip()
    .astype(float)
)

In [8]:
car_clean[["lat", "long"]].head()

         lat      long
0  47.562770  6.758320
1  47.021090  4.837550
2  44.902384  2.496418
3  49.191660 -0.398510
4  43.390000  5.350000

In [9]:
car_clean[["lat", "long"]].dtypes

lat     float64
long    float64
dtype: object

In [10]:
car_clean["Hour"] = car_clean["hrmn"].str.split(":").str[0].astype(int)

In [11]:
car_clean[["hrmn", "Hour"]].head(10)

    hrmn  Hour
0  07:40     7
1  15:05    15
2  19:30    19
3  17:50    17
4  19:35    19
5  04:00     4
6  02:45     2
7  14:45    14
8  03:40     3
9  19:50    19

In [12]:
car_clean["Hour"].dtype

dtype('int64')

In [13]:
car_clean.isnull().sum()

Num_Acc       0
jour          0
mois          0
an            0
hrmn          0
lum           0
dep           0
com           0
agg           0
int           0
atm           0
col           0
adr        2310
lat           0
long          0
Hour          0
dtype: int64

In [14]:
car_clean["adr"] = car_clean["adr"].fillna("Unknown")

In [15]:
car_clean["adr"].isnull().sum()

np.int64(0)

In [16]:
car_clean.duplicated().sum()

np.int64(0)

In [17]:
car_clean.describe()

,Num_Acc,jour,mois,an,lum,agg,int,atm,col,lat,long,Hour
count,5.440200e+04,54402.000000,54402.000000,54402.0,54402.000000,54402.000000,54402.000000,54402.000000,54402.000000,54402.000000,54402.000000,54402.000000
mean,2.024000e+11,15.665490,6.615749,2024.0,1.949708,1.625161,2.108195,1.677493,4.018069,44.051229,1.240096,13.358774
std,1.570465e+04,8.737761,3.361701,0.0,1.488462,0.484086,2.042602,1.736956,1.984560,12.665655,19.460609,5.638434
min,2.024000e+11,1.000000,1.000000,2024.0,1.000000,1.000000,1.000000,1.000000,-1.000000,-22.433239,-178.094387,0.000000
25%,2.024000e+11,8.000000,4.000000,2024.0,1.000000,1.000000,1.000000,1.000000,3.000000,44.519282,1.153567,9.000000
50%,2.024000e+11,16.000000,7.000000,2024.0,1.000000,2.000000,1.000000,1.000000,3.000000,47.717121,2.392034,14.000000
75%,2.024000e+11,23.000000,10.000000,2024.0,3.000000,2.000000,2.000000,1.000000,6.000000,48.861732,4.732405,18.000000
max,2.024001e+11,31.000000,12.000000,2024.0,5.000000,2.000000,9.000000,9.000000,7.000000,51.078740,167.863219,23.000000

In [18]:
car_clean[["lum", "agg", "int", "atm", "col"]].isin([-1]).sum()

lum    0
agg    0
int    0
atm    0
col    6
dtype: int64

In [19]:
car_clean["col"].value_counts().sort_index()

col
-1        6
 1     6057
 2     7162
 3    16371
 4     1821
 5     1554
 6    15968
 7     5463
Name: count, dtype: int64

In [20]:
import numpy as np

car_clean["col"] = car_clean["col"].replace(-1, np.nan)

In [21]:
car_clean["col"].isnull().sum()

np.int64(6)

In [22]:
car_clean["lum"].value_counts().sort_index()

lum
1    35580
2     3599
3     6101
4      623
5     8499
Name: count, dtype: int64

In [23]:
car_clean["atm"].value_counts().sort_index()

atm
1    41802
2     6779
3     1449
4      233
5      529
6      169
7      817
8     2374
9      250
Name: count, dtype: int64

In [24]:
car_clean["agg"].value_counts().sort_index()

agg
1    20392
2    34010
Name: count, dtype: int64

In [25]:
car_clean["int"].value_counts().sort_index()

int
1    34589
2     6289
3     6451
4     1048
5      263
6     2717
7      453
8      138
9     2454
Name: count, dtype: int64

In [26]:
car_clean["dep"].value_counts().head(20)

dep
75     4191
93     2640
92     2485
13     2120
94     1963
69     1627
91     1348
33     1202
77     1068
59     1023
95      943
974     934
64      880
83      866
44      812
34      798
06      783
76      752
78      728
29      721
Name: count, dtype: int64

In [27]:
car_clean["dep"].dtype

In [28]:
sorted(car_clean["dep"].unique())

['01',
 '02',
 '03',
 '04',
 '05',
 '06',
 '07',
 '08',
 '09',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '2A',
 '2B',
 '30',
 '31',
 '32',
 '33',
 '34',
 '35',
 '36',
 '37',
 '38',
 '39',
 '40',
 '41',
 '42',
 '43',
 '44',
 '45',
 '46',
 '47',
 '48',
 '49',
 '50',
 '51',
 '52',
 '53',
 '54',
 '55',
 '56',
 '57',
 '58',
 '59',
 '60',
 '61',
 '62',
 '63',
 '64',
 '65',
 '66',
 '67',
 '68',
 '69',
 '70',
 '71',
 '72',
 '73',
 '74',
 '75',
 '76',
 '77',
 '78',
 '79',
 '80',
 '81',
 '82',
 '83',
 '84',
 '85',
 '86',
 '87',
 '88',
 '89',
 '90',
 '91',
 '92',
 '93',
 '94',
 '95',
 '971',
 '972',
 '973',
 '974',
 '975',
 '976',
 '977',
 '978',
 '986',
 '987',
 '988']

In [29]:
department_names = {
    "01": "Ain",
    "02": "Aisne",
    "03": "Allier",
    "04": "Alpes-de-Haute-Provence",
    "05": "Hautes-Alpes",
    "06": "Alpes-Maritimes",
    "07": "Ardèche",
    "08": "Ardennes",
    "09": "Ariège",
    "10": "Aube",
    "11": "Aude",
    "12": "Aveyron",
    "13": "Bouches-du-Rhône",
    "14": "Calvados",
    "15": "Cantal",
    "16": "Charente",
    "17": "Charente-Maritime",
    "18": "Cher",
    "19": "Corrèze",
    "2A": "Corse-du-Sud",
    "2B": "Haute-Corse",
    "21": "Côte-d'Or",
    "22": "Côtes-d'Armor",
    "23": "Creuse",
    "24": "Dordogne",
    "25": "Doubs",
    "26": "Drôme",
    "27": "Eure",
    "28": "Eure-et-Loir",
    "29": "Finistère",
    "30": "Gard",
    "31": "Haute-Garonne",
    "32": "Gers",
    "33": "Gironde",
    "34": "Hérault",
    "35": "Ille-et-Vilaine",
    "36": "Indre",
    "37": "Indre-et-Loire",
    "38": "Isère",
    "39": "Jura",
    "40": "Landes",
    "41": "Loir-et-Cher",
    "42": "Loire",
    "43": "Haute-Loire",
    "44": "Loire-Atlantique",
    "45": "Loiret",
    "46": "Lot",
    "47": "Lot-et-Garonne",
    "48": "Lozère",
    "49": "Maine-et-Loire",
    "50": "Manche",
    "51": "Marne",
    "52": "Haute-Marne",
    "53": "Mayenne",
    "54": "Meurthe-et-Moselle",
    "55": "Meuse",
    "56": "Morbihan",
    "57": "Moselle",
    "58": "Nièvre",
    "59": "Nord",
    "60": "Oise",
    "61": "Orne",
    "62": "Pas-de-Calais",
    "63": "Puy-de-Dôme",
    "64": "Pyrénées-Atlantiques",
    "65": "Hautes-Pyrénées",
    "66": "Pyrénées-Orientales",
    "67": "Bas-Rhin",
    "68": "Haut-Rhin",
    "69": "Rhône",
    "70": "Haute-Saône",
    "71": "Saône-et-Loire",
    "72": "Sarthe",
    "73": "Savoie",
    "74": "Haute-Savoie",
    "75": "Paris",
    "76": "Seine-Maritime",
    "77": "Seine-et-Marne",
    "78": "Yvelines",
    "79": "Deux-Sèvres",
    "80": "Somme",
    "81": "Tarn",
    "82": "Tarn-et-Garonne",
    "83": "Var",
    "84": "Vaucluse",
    "85": "Vendée",
    "86": "Vienne",
    "87": "Haute-Vienne",
    "88": "Vosges",
    "89": "Yonne",
    "90": "Territoire de Belfort",
    "91": "Essonne",
    "92": "Hauts-de-Seine",
    "93": "Seine-Saint-Denis",
    "94": "Val-de-Marne",
    "95": "Val-d'Oise",
    "971": "Guadeloupe",
    "972": "Martinique",
    "973": "Guyane",
    "974": "La Réunion",
    "975": "Saint-Pierre-et-Miquelon",
    "976": "Mayotte",
    "977": "Saint-Barthélemy",
    "978": "Saint-Martin",
    "986": "Wallis-et-Futuna",
    "987": "Polynésie française",
    "988": "Nouvelle-Calédonie"
}

In [30]:
car_clean["Department"] = car_clean["dep"].map(department_names)

In [31]:
car_clean[["dep", "Department"]].drop_duplicates().sort_values("dep").head(20)

     dep               Department
93    01                      Ain
169   02                    Aisne
555   03                   Allier
140   04  Alpes-de-Haute-Provence
138   05             Hautes-Alpes
9     06          Alpes-Maritimes
7     07                  Ardèche
383   08                 Ardennes
1145  09                   Ariège
83    10                     Aube
283   11                     Aude
191   12                  Aveyron
4     13         Bouches-du-Rhône
3     14                 Calvados
2     15                   Cantal
534   16                 Charente
167   17        Charente-Maritime
206   18                     Cher
514   19                  Corrèze
1     21                Côte-d'Or

In [32]:
lum_names = {
    1: "Daylight",
    2: "Twilight or dawn",
    3: "Night - public lighting on",
    4: "Night - public lighting off",
    5: "Night - no public lighting"
}

car_clean["Light_Condition"] = car_clean["lum"].map(lum_names)

In [33]:
car_clean[["lum", "Light_Condition"]].drop_duplicates().sort_values("lum")

    lum              Light_Condition
1     1                     Daylight
0     2             Twilight or dawn
8     3   Night - public lighting on
65    4  Night - public lighting off
4     5   Night - no public lighting

In [34]:
weather_names = {
    1: "Normal",
    2: "Light rain",
    3: "Heavy rain",
    4: "Snow or hail",
    5: "Fog or smoke",
    6: "Strong wind",
    7: "Dazzling weather",
    8: "Overcast",
    9: "Other"
}

car_clean["Weather_Condition"] = car_clean["atm"].map(weather_names)

In [35]:
car_clean[["atm", "Weather_Condition"]].drop_duplicates().sort_values("atm")

      atm Weather_Condition
2       1            Normal
4       2        Light rain
68      3        Heavy rain
1589    4      Snow or hail
0       5      Fog or smoke
805     6       Strong wind
1       7  Dazzling weather
55      8          Overcast
108     9             Other

In [36]:
agg_names = {
    1: "Within an urban area",
    2: "Outside an urban area"
}

car_clean["Location_Type"] = car_clean["agg"].map(agg_names)

In [37]:
car_clean[["agg", "Location_Type"]].drop_duplicates().sort_values("agg")

   agg          Location_Type
0    1   Within an urban area
1    2  Outside an urban area

In [38]:
int_names = {
    1: "Out of intersection",
    2: "X intersection",
    3: "T intersection",
    4: "Y intersection",
    5: "More than 4 branches",
    6: "Giratory",
    7: "Place",
    8: "Railway crossing",
    9: "Other"
}

car_clean["Intersection_Type"] = car_clean["int"].map(int_names)

In [39]:
car_clean[["int", "Intersection_Type"]].drop_duplicates().sort_values("int")

     int     Intersection_Type
0      1   Out of intersection
5      2        X intersection
1      3        T intersection
94     4        Y intersection
465    5  More than 4 branches
61     6              Giratory
183    7                 Place
675    8      Railway crossing
74     9                 Other

In [40]:
collision_names = {
    1: "Two vehicles - frontal",
    2: "Two vehicles - rear-end",
    3: "Two vehicles - side",
    4: "Three or more vehicles - chain",
    5: "Three or more vehicles - multiple collisions",
    6: "Other collision",
    7: "No collision"
}

car_clean["Collision_Type"] = car_clean["col"].map(collision_names).fillna("Unknown")

In [41]:
car_clean[["col", "Collision_Type"]].drop_duplicates().sort_values("col")

     col                                Collision_Type
0    1.0                        Two vehicles - frontal
7    2.0                       Two vehicles - rear-end
3    3.0                           Two vehicles - side
24   4.0                Three or more vehicles - chain
4    5.0  Three or more vehicles - multiple collisions
1    6.0                               Other collision
9    7.0                                  No collision
953  NaN                                       Unknown

In [42]:
car_clean.shape

(54402, 22)

In [43]:
car_clean.isnull().sum()

Num_Acc              0
jour                 0
mois                 0
an                   0
hrmn                 0
lum                  0
dep                  0
com                  0
agg                  0
int                  0
atm                  0
col                  6
adr                  0
lat                  0
long                 0
Hour                 0
Department           0
Light_Condition      0
Weather_Condition    0
Location_Type        0
Intersection_Type    0
Collision_Type       0
dtype: int64

In [44]:
car_clean.head()

,Num_Acc,jour,mois,an,hrmn,lum,dep,com,agg,int,...,adr,lat,long,Hour,Department,Light_Condition,Weather_Condition,Location_Type,Intersection_Type,Collision_Type
0,202400000001,25,3,2024,07:40,2,70,70285,1,1,...,D438,47.562770,6.758320,7,Haute-Saône,Twilight or dawn,Fog or smoke,Within an urban area,Out of intersection,Two vehicles - frontal
1,202400000002,20,3,2024,15:05,1,21,21054,2,3,...,HOTEL DIEU (RUE DE L'),47.021090,4.837550,15,Côte-d'Or,Daylight,Dazzling weather,Outside an urban area,T intersection,Other collision
2,202400000003,22,3,2024,19:30,2,15,15012,1,1,...,Allée des Tilleuls,44.902384,2.496418,19,Cantal,Twilight or dawn,Normal,Within an urban area,Out of intersection,Other collision
3,202400000004,24,3,2024,17:50,1,14,14118,2,3,...,128 Rue d'Authie,49.191660,-0.398510,17,Calvados,Daylight,Dazzling weather,Outside an urban area,T intersection,Two vehicles - side
4,202400000005,25,3,2024,19:35,5,13,13106,1,3,...,BEDOULE (CHEMIN DE LA),43.390000,5.350000,19,Bouches-du-Rhône,Night - no public lighting,Light rain,Within an urban area,T intersection,Three or more vehicles - multiple collisions

In [45]:
car_clean["Date"] = pd.to_datetime(
    car_clean["an"].astype(str) + "-" +
    car_clean["mois"].astype(str) + "-" +
    car_clean["jour"].astype(str)
)

In [46]:
car_clean[["jour", "mois", "an", "Date"]].head()

   jour  mois    an       Date
0    25     3  2024 2024-03-25
1    20     3  2024 2024-03-20
2    22     3  2024 2024-03-22
3    24     3  2024 2024-03-24
4    25     3  2024 2024-03-25

In [47]:
car_clean["Month_Name"] = car_clean["Date"].dt.month_name()

In [48]:
car_clean["Day_Name"] = car_clean["Date"].dt.day_name()

In [49]:
car_clean[["Date", "Month_Name", "Day_Name"]].head(10)

        Date Month_Name   Day_Name
0 2024-03-25      March     Monday
1 2024-03-20      March  Wednesday
2 2024-03-22      March     Friday
3 2024-03-24      March     Sunday
4 2024-03-25      March     Monday
5 2024-03-25      March     Monday
6 2024-03-24      March     Sunday
7 2024-03-24      March     Sunday
8 2024-03-24      March     Sunday
9 2024-03-25      March     Monday

In [50]:
car_clean["Month_Name"] = car_clean["Date"].dt.month_name()
car_clean["Day_Name"] = car_clean["Date"].dt.day_name()

In [51]:
car_clean.to_csv(
    "caracteristiques_2024_clean.csv",
    index=False,
    encoding="utf-8-sig"
)

In [52]:
import os

os.path.exists("caracteristiques_2024_clean.csv")

True

In [53]:
import os

print(os.getcwd())

C:\Users\omare\Road Accidents Analysis

In [54]:
import os

print(os.listdir())

['.ipynb_checkpoints', '01_data_understanding.ipynb', 'caracteristiques_2024_clean.csv', 'data']

In [55]:
print(car_clean.shape)
print(car_clean.columns.tolist())

(54402, 25)
['Num_Acc', 'jour', 'mois', 'an', 'hrmn', 'lum', 'dep', 'com', 'agg', 'int', 'atm', 'col', 'adr', 'lat', 'long', 'Hour', 'Department', 'Light_Condition', 'Weather_Condition', 'Location_Type', 'Intersection_Type', 'Collision_Type', 'Date', 'Month_Name', 'Day_Name']

In [56]:
test = pd.read_csv("caracteristiques_2024_clean.csv")

print(test.shape)
print(test.columns.tolist())

(54402, 25)
['Num_Acc', 'jour', 'mois', 'an', 'hrmn', 'lum', 'dep', 'com', 'agg', 'int', 'atm', 'col', 'adr', 'lat', 'long', 'Hour', 'Department', 'Light_Condition', 'Weather_Condition', 'Location_Type', 'Intersection_Type', 'Collision_Type', 'Date', 'Month_Name', 'Day_Name']

In [57]:
test = pd.read_csv("caracteristiques_2024_clean.csv")

print(test.shape)
print(test.columns.tolist())

(54402, 25)
['Num_Acc', 'jour', 'mois', 'an', 'hrmn', 'lum', 'dep', 'com', 'agg', 'int', 'atm', 'col', 'adr', 'lat', 'long', 'Hour', 'Department', 'Light_Condition', 'Weather_Condition', 'Location_Type', 'Intersection_Type', 'Collision_Type', 'Date', 'Month_Name', 'Day_Name']